example/server.lhs
The server looks for "Hi! I am..." rather than "Hi, I am..."
=> Corrected the format

src/Network/WebSockets/Server.hs
The function is not recommended for real world usage, but still it is useful to make it exception-safe.
=> Exception safety in runServer

src/Network/WebSockets.hs, src/Network/WebSockets/Server.hs
Hi!
I'd like to propose the following change: Use a `Stream` argument for `makePendingConnection` instead of a `Socket`. This allows the use of more general streams, e.g. for a TLS connection. Currently, this is the easiest and cleanest solution since it is not possible to implement something like `makePendingConnection` outside of the websockets library because of the `decodeRequestHead` function, which is a private function from the hidden module `Network.Websockets.HTTP`.
This change does break the current API, but I think it is a reasonable change and easy to fix for any users of this function (see e.g. the change in `runApp`).
– McManiaC
=> Change makePendingConnection to accept a Stream instead of a Socket

websockets.cabal
```
src/Network/WebSockets/Server.hs:17:49:
Module `Control.Concurrent' does not export `forkIOWithUnmask'
```
I added revisions for this: https://hackage.haskell.org/package/websockets-0.9.6.2/revisions/
=> Needs GHC >= 7.2 due to usage of forkIOWithUnmask

src/Network/WebSockets/Connection.hs, tests/haskell/Network/WebSockets/Handshake/Tests.hs
Add `acceptHeaders` field to `AcceptRequest` so that extra headers can
be sent back with the response when using `acceptRequestWith`.
This is useful for example for sending back a `Set-Cookie` header with a
session ID, etc.
=> Allow sending extra headers when accepting request

src/Network/WebSockets.hs, src/Network/WebSockets/Connection.hs, src/Network/WebSockets/Hybi13.hs, src/Network/WebSockets/Protocol.hs, tests/haskell/Network/WebSockets/Server/Tests.hs, tests/haskell/Network/WebSockets/Tests.hs
For discussion, for now.
Looking into the performance issues as discussed in https://github.com/bitemyapp/websocket-shootout/pull/3 I believe it would be useful to be able to send a list of messages all at once, rather than sending them one-at-a-time.
This PR, as it currently stands, extends the `websockets` API just enough to support this, and it does seem to help performance-wise.
If encouraged, I'll put some effort into finishing it off and making it mergeworthy. I'm a little unhappy with how things are named, so advice on better names is most welcome.
=> Allow sending of collections of messages all at once

benchmarks/mask.hs, src/Network/WebSockets/Hybi13/Mask.hs, websockets.cabal
The motivation for caring about zero mask specifically is that clients can choose it for performance reasons, especially when communication is going over TLS and you don't have to care about obfuscating stuff.
=> Faster masking, also add a benchmark

src/Network/WebSockets/Client.hs, src/Network/WebSockets/Server.hs, tests/haskell/Network/WebSockets/Server/Tests.hs
This patch adds support for IPv6 addressing in the client, the server, and tests. All tests pass under Ubuntu 12.04.
=> add IPv6 support

websockets.cabal
This typo prevented `cabal bench`/`stack bench` from working.
=> Fix typo in benchmark definition in cabal file

benchmarks/mask.hs, cbits/cbits.c, src/Network/WebSockets/Hybi13.hs, src/Network/WebSockets/Hybi13/Mask.hs, src/Network/WebSockets/Server.hs, src/Network/WebSockets/Stream.hs, tests/haskell/Network/WebSockets/Mask/Tests.hs, tests/haskell/TestSuite.hs, websockets.cabal
This is a merge against the fast-mask branch.
- Changed mask to be `Word32`
- Changed the frame parser to use `binary`
- Changed blocksize on received data to 8192
- Fixed C-code, changed it to do just 1 copy
- Added quickcheck for the masking code
It seems to me there are still some unnecessary bytestrings in memory, but it is some fixed memory per connection (~ 15K), it doesn't seem to change depending on the traffic on the socket.
=> Performance tweaks

src/Network/WebSockets/Http.hs, tests/haskell/Network/WebSockets/Http/Tests.hs
This PR fixes the parsing of the message or "reason-phrase" part of the response status line. According to [the specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html) it is allowed to be empty while the library required it to have non-zero width. Please see, for example, [this SO thread](https://stackoverflow.com/q/17517086/8051150) for discussion.
=> Fix reason phrase parsing

src/Network/WebSockets/Hybi13.hs, src/Network/WebSockets/Stream.hs
There seems to be a space leak related to the use of `atomicModifyIORef` (i.e. the non-strict variant) in the context of encoding messages in [Network.WebSockets.Hybi13](https://github.com/jaspervdj/websockets/blob/master/src/Network/WebSockets/Hybi13.hs#L92-L118). Specifically, in a server application, it appears that `gen'` is never forced, thus building up a chain of thunks during the lifetime of a connection as messages are sent by the server. The following results are from a test setup with 1000 clients sending a ping every second (to which the server responds with a pong) for a duration of 5 minutes. I also attached the complete sample project, just in case.
`atomicModifyIORef`
`atomicModifyIORef'`
Sources: 
[websockets-leak.zip](https://github.com/jaspervdj/websockets/files/1139427/ …
=> Use strict atomicModifyIORef'.

src/Network/WebSockets.hs, src/Network/WebSockets/Client.hs, src/Network/WebSockets/Connection.hs, src/Network/WebSockets/Connection/Options.hs, src/Network/WebSockets/Extensions/PermessageDeflate.hs, src/Network/WebSockets/Hybi13.hs, src/Network/WebSockets/Hybi13/Demultiplex.hs, src/Network/WebSockets/Protocol.hs, src/Network/WebSockets/Types.hs, tests/haskell/Network/WebSockets/Extensions/PermessageDeflate/Tests.hs, tests/haskell/Network/WebSockets/Hybi13/Demultiplex/Tests.hs, tests/haskell/Network/WebSockets/Tests.hs, tests/haskell/TestSuite.hs, websockets.cabal
This allows you to set limits for the frame and message sizes to prevent (D)DoS attacks.
See also #149
=> Add limit options for frame and message size

src/Network/WebSockets/Connection/Options.hs
Fixes #163.  Tested on GHC 8.4.1-alpha1 and 8.0.2.
=> Options.hs:SizeLimit:  add Semigroup instance (GHC 8.4 compat)

CHANGELOG, websockets.cabal
This allows for recent version(s) of `streaming-commons` that have dropped the dependency on `blaze-builder`.
=> relax upper bound for streaming-commons

example/server.lhs
We can find the connection in the client tuple, so it's one less argument to pass to the `talk`function.
=> Slight simplification in server.lhs

CHANGELOG, src/Network/WebSockets/Client.hs
And could you please deprecate the 0.12.5.0 release?
It would also be great if CI could cover these GHC versions.
=> Fix build with GHC 7.6 and 7.8

src/Network/WebSockets/Client.hs, websockets.cabal
I'm using [hspec-wai](https://hackage.haskell.org/package/hspec-wai) to test my HTTP APIs and would like to be able to also test my websocket end points in the same test-suite. 
The idea of hspec-wai is that the test suit runs the WAI handlers directly instead of communicating with them through a web server. This means that requests are not serialized into wire format. However, in the case of wai-websockets, the _response_ is a pair of serialized octet-streams. These streams are easily adapted to websocket's `stream` type, but there is no function that accepts either a half- or a completely negotiated websocket connection. 
To allow for this I've factored out `mkConnection` and `checkServerResponse` from `newClientConnection` and also exported `createRequest`, `Protocol(..)` and …
=> Implement more fine-grained construction of client Connection

websockets.cabal
Tested using
cabal test --constraint='text>=2.0'
NOTE: The failing CI doesn't look like it is because of this PR. It seems to be because Stack metadata moved servers.
=> Allow text-2.0

.circleci/config.yml, tests/autobahn/autobahn.sh
Stack was not managing to get a GHC running, even with the `--system-ghc` flag. So I switched the project to `cabal-install`.
The test suite results for this PR can be seen at https://app.circleci.com/pipelines/github/ysangkok/websockets?branch=ghc-9.0-in-ci&filter=all
=> Use GHC 9.0 in CI

websockets.cabal
`instance Random Word32` is not available in `random-1.0.0.*`.
As a Hackage trustee I made revisions:
https://hackage.haskell.org/package/websockets-0.12.7.2/revisions/
https://hackage.haskell.org/package/websockets-0.12.7.3/revisions/
=> Require random >= 1.0.1

src/Network/WebSockets/Connection.hs
Hi! I've been playing around with various cryptocurrency exchange APIs using this library (+wuss) and I'm loving it so far. However, I've come across an unusual situation. There are certain servers that seem to expect unsolicited Pongs (?!) to keep the connection alive. So I've added a way to manually send the Pong messages. It's a fairly small addition - basically identical to the sendPing function. Hope you can merge. Let me know if I need to add anything else.
Thanks!
=> Added a way to manually send a Pong message.

websockets.cabal
I've removed a bunch of dependencies for examples that aren't needed and removed the bounds (as they are already enforced in the library itself and not used beyond the simple type imports).
=> add client-example executable

src/Network/WebSockets/Http.hs, src/Network/WebSockets/Hybi13.hs, tests/haskell/Network/WebSockets/Server/Tests.hs
While this is technically a breaking change in the API, `RequestRejected` was never raised before.
Fixes #134 
cc @jaspervdj
=> Client: correctly reject request

src/Network/WebSockets/Stream.hs, websockets.cabal
=> if socket raises an exception that resource vanished, consider it closed

CHANGELOG, README.md, src/Network/WebSockets.hs, src/Network/WebSockets/Client.hs, src/Network/WebSockets/Connection.hs, src/Network/WebSockets/Connection/PingPong.hs, src/Network/WebSockets/Server.hs, websockets.cabal
Because the Server used only pong implementation it's not possible to keep backwards compatibility with the new implementation that also does pinging.
Fixes #159
cc @jaspervdj
=> Add ping-pong implementation that handles stale connections.

src/Network/WebSockets/Client.hs, src/Network/WebSockets/Connection/Options.hs, src/Network/WebSockets/Http.hs
=> Client: default to 30s for connection timeout

CHANGELOG, websockets.cabal
=> Bump version to 0.13.0.0
